### ISSUE TITLE
Performance optimization Gaussian components

### ISSUE THREAD

**Issue by zonca** [simonsobs/so_pysm_models#11]
@NicolettaK I am benchmarking the map-based simulations (https://github.com/simonsobs/mapsims/issues/13) and `GaussianSynchrotron` and `GaussianDust` dominate computing time due to the `while` loops, it often happens that 9-10 iterations are done to compute one realization.

For example at 1024 it takes 6 minutes each and it gets way worse at higher NSIDE.

Do you think there is a reasonable alternative instead of looping?

**Comment by NicolettaK** [comment]
I will run some test to understand how to optimize the code. Nevertheless I understood from the telecon yesterday that we do not need many realizations

**Comment by zonca** [comment]
yes, @NicolettaK don't worry much about this.
I was just wondering: isn't it an option to add a monopole to avoid negative values? In my understanding we do not care about monopoles anyway.

**Comment by NicolettaK** [comment]
@zonca I think I found an easy way to nicely solve the problem, I'll implement it and push it tomorrow.

**Comment by NicolettaK** [comment]
@zonca pull request https://github.com/simonsobs/so_pysm_models/pull/12# should solve the issue
