### ISSUE TITLE
New templates to be copied at NERSC

### ISSUE THREAD

**Issue by NicolettaK** [simonsobs/so_pysm_models#29]
@zonca I'm working at the new set of models with spatially varying spectral indices.
There are few maps which need to be copied on the NERSC web hosting.
You can find them on my scratch at NERSC, here:
`/global/cscratch1/sd/krach/SObs/FGawg/so_template`

they are:
`beta_dust_ns512_1deg.fits`
`beta_dust_ns4096_1deg.fits`
`temperature_dust_ns512_1deg.fits`
`temperature_dust_ns4096_1deg.fits`
`beta_synch_ns512_1deg.fits`
`beta_synch_ns4096_1deg.fits`
`ame_nu0_peak_ns512_1deg.fits`
`ame_nu0_peak_ns4096_1deg.fits`

thanks!

**Comment by zonca** [comment]
ok,
I put them in a subfolder, see http://portal.nersc.gov/project/cmb/so_pysm_models_data/variable_spectral_index/

so you can get them in the Python code as:

`variable_spectral_index/*.fits`

**Comment by NicolettaK** [comment]
Thanks! Probably it is better to have sub-folders with the name of emission like `dust` or `synchrotron`. 
`variable_spectral_index` is not correct as there are also maps modeling the variation of dust temperature or ame peak frequency.
Could you do that?
