### ISSUE TITLE
Create unit test for Gaussian Synchrotron

### ISSUE THREAD

**Issue by zonca** [simonsobs/so_pysm_models#3]
@NicolettaK it would be useful to have a simple test to check my implementation,
can you run a gaussian synchrotron realization with your own tools at NSIDE 16 and with a specific random seed (https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html) and attach the result in FITS format to this issue?

I'll then use it to create a unit test for my implementation.

**Comment by zonca** [comment]
Better have the outputs in K_RJ, by default PySM components use RJ, then PySM converts them to K_CMB if needed

**Comment by NicolettaK** [comment]
@zonca attached the synchrotron map for unit test, nside=16, RJ units. 
It has been generated with `np.random.seed(31)`
[Gaussian_synch_23GHz_uRJ_testmap.fits.zip](https://github.com/simonsobs/so_pysm_models/files/2652586/Gaussian_synch_23GHz_uRJ_testmap.fits.zip)

**Comment by zonca** [comment]
thanks, unit test created in 2ae587a292ad01eed5443b5375e4facd333a681d,
I'll override this with a full IQU map once we have T sims working.

**Comment by zonca** [comment]
ok, thanks
