### ISSUE TITLE
Copy new websky maps from sobs project space to cmb space on nersc 

### ISSUE THREAD

**Issue by marcelo-alvarez** [simonsobs/so_pysm_models#31]
Please copy contents of 
  /project/projectdirs/sobs/v4_sims/mbs/websky/0.3
to 
  /global/project/projectdirs/cmb/www/so_pysm_models_data/websky/0.3

**Comment by zonca** [comment]
they are symlinks, that messes up my scripts.
can you create please  a folder with real files?

**Comment by zonca** [comment]
worse than that, they are broken symlinks

**Comment by marcelo-alvarez** [comment]
broken symlinks are worse indeed. 
all the files in that directory are now real files.

**Comment by zonca** [comment]
thanks, copied:

https://portal.nersc.gov/project/cmb/so_pysm_models_data/websky/0.3/
