### ISSUE TITLE
Possible mismatch of coordinate system in high-res Galactic sims and noise

### ISSUE THREAD

**Issue by msyriac** [simonsobs/so_pysm_models#35]
The high resolution Galactic templates seem to be in Galactic coordinates while the hit maps for noise simulations seem to be in Equatorial coordinates. Could someone else confirm this? If this is the case, we should fix it, preferably by outputting all maps in Equatorial coordinates.

**Comment by NicolettaK** [comment]
Yes, I confirm, we also noticed that. Thanks for posting it here. Shall we rotate the Galactic maps?

**Comment by msyriac** [comment]
Yes, please go ahead and rotate the Galactic maps to Equatorial coordinates. Thank you!

**Comment by zonca** [comment]
great that someone is looking at the maps! ;)
I would prefer to rotate regenerate the noise maps directly Galactic coordinates, as all the templates are in Galactic reference anyway.

**Comment by msyriac** [comment]
@zonca : @humnaawan and I are using these maps right now for an SOxLSST investigation and hope to report on results with it and contribute to any necessary debugging/iteration.

The ACT maps are generated in Equatorial coordinates, so my preference is for Equatorial, but I could be persuaded otherwise. @mhasself @amaurea do you see this changing with SO? We should try and converge on a choice of mapping coordinate system soon.

**Comment by msyriac** [comment]
Thinking about this a bit more, many pipelines use k-space filtering, which is most naturally done in the coordinate system that the noise lives in (Equatorial). So I think it definitely makes sense to rotate the Galactic templates to Equatorial rather than rotating the noise.

**Comment by zonca** [comment]
We had a discussion of the simulation parameters before the first sim and
everyone agreed on galactic reference frame.
I'm fine with changing but we need feedback.
So, can you please open an issue on the map_based_simulations repo about
switching to equatorial and ask for feedback on Slack?

**Comment by msyriac** [comment]
I seem to have missed that discussion, but yes, I agree that we should get feedback. I've raised an issue here: https://github.com/simonsobs/map_based_simulations/issues/5 and will advertise on slack.

**Comment by msyriac** [comment]
@NicolettaK , the issue at https://github.com/simonsobs/map_based_simulations/issues/5 is closed and we've decided to proceed with rotating the high-res Galactic templates to Equatorial.

**Comment by NicolettaK** [comment]
ok thanks. Does anyone have a reliable python code to rotate maps? @zonca ?

**Comment by zonca** [comment]
it is just easier to rerun the high res foregrounds simulations, I'll take care of that.
