### ISSUE TITLE
CAR support broken; affects mapsims/cmb.py

### ISSUE THREAD

**Issue by msyriac** [simonsobs/so_pysm_models#42]
This commit 78a61fc4a9c3f103f265472342e6bae52ef8d754 removed all CAR support. I'm not sure how this didn't break all the mapsism tests, since keywords like target_shape and target_wcs are explicitly referenced in mapsims/cmb.py https://github.com/simonsobs/mapsims/blob/master/mapsims/cmb.py .

@zonca What was the rationale for removing this support? If you feel there weren't enough tests, please raise an issue for that, rather than removing optional features that break entire modules elsewhere.

**Comment by zonca** [comment]
Sorry I thought it was unused.
I'll review and merge it later on.
I'm restructuring mapsims to support bands like MFF1.
