### ISSUE TITLE
Memory usage in extragalactic

### ISSUE THREAD

**Issue by zonca** [simonsobs/so_pysm_models#45]
@keskitalo I just realized that the memory issue you were seeing is possibly due to the extragalactic models being just at nside 4096, see https://portal.nersc.gov/project/cmb/so_pysm_models_data/equatorial/websky/0.3/.

Moreover, in CIB we are interpolating, so we can load even 5 different models, you can check in the logs how many exactly for your case.

I wonder if we should provide 512 versions of all those maps.

**Comment by keskitalo** [comment]
Yes please!

**Comment by zonca** [comment]
@marcelo-alvarez can I just use `ud_grade` to create a nside 512 version of the templates or you have a better recommendation?

**Comment by marcelo-alvarez** [comment]
you can, these are intensity maps and so the pixel averaging should be exactly correct with ud_grade.

**Comment by zonca** [comment]
@keskitalo I have implemented this, if you request extragalactic at NSIDE 512 or lower, it automatically downloads (or accesses if running at NERSC) the NSIDE 512 maps. Can you please update `so_pysm_models` and submit a quick run to confirm this is working?

**Comment by keskitalo** [comment]
I confirm that the memory consumption is reduced.

**Comment by zonca** [comment]
Thanks!
