### ISSUE TITLE
Tensor modes compatible with the Websky CMB

### ISSUE THREAD

**Issue by zonca** [simonsobs/so_pysm_models#48]
@marcelo-alvarez @ajvanengelen Would it be possible for you to run a simulation of just the primordial B modes (no lensing) with the same cosmological parameters used for the WebSky CMB simulations?
Using a fiducial value of `r` (any would work, e.g. 1e-3).

Then I can add an option to the [`WebSkyCMB`](https://so-pysm-models.readthedocs.io/en/latest/api/so_pysm_models.WebSkyCMB.html#so_pysm_models.WebSkyCMB) to specify a value of `r` and add those primordial B modes properly weighted.

**Comment by ajvanengelen** [comment]
Hi Andra,

A model with tensors would have a TT component at low-ell (ell < 80), as well.  So would we simply turn that off?

Also, would it be enough for us to give the BB theory power spectrum, and let your own end of the code take care of generating a gaussian random field with this power spectrum?  Just asking about what is the most straightforward path here.  (If no lensing is required, then perhaps on-the-fly sims are easier to deal with).

Alex


________________________________

**Comment by zonca** [comment]
@ajvanengelen @keskitalo I think we can keep the TT low-ell component as well.

Yes, thanks, just `C_{ell}` is enough

**Comment by zonca** [comment]
@ajvanengelen any news about this?

**Comment by zonca** [comment]
@ajvanengelen would you have any update about this?

**Comment by ajvanengelen** [comment]
Hi Andrea, did you see my update of Feb 29th?
Alex
________________________________

**Comment by zonca** [comment]
no

**Comment by ajvanengelen** [comment]
OK, not sure how this github forum works, I thought you could reply to these notifications from email.  I just forwared you my update (with a pointer to the data) to your sdsc.edu email.
Alex
________________________________

**Comment by zonca** [comment]
From @ajvanengelen: 

NERSC:

    /global/cscratch1/sd/engelen/websky_BB_from_tensors_r_eq_1.npz.npy

> This is the BB spectrum for the Websky cosmology from a model with r = 1 (which of course needs to be scaled to whatever actual r value we want to use).  It is in the format that pixell expects for power spectra, namely an array of shape (3, 3, N_ell) and so the spectrum is in the [2, 2, :] elements.  Units are plain C_l in uK^2.

**Comment by zonca** [comment]
thanks @ajvanengelen!
I'll implement this into the model

**Comment by zonca** [comment]
if anyone is willing to help implement this:

- [ ] load the `npy` file, check units are reasonable, save in FITS
- [ ] implement an argument `tensor_scalar_ratio=0` in `WebSkyCMB` https://github.com/simonsobs/so_pysm_models/blob/master/so_pysm_models/extragalactic.py#L164 which loads this thing with a specific seed, creates a map and sums it
- [ ] implement a unit test in https://github.com/simonsobs/so_pysm_models/blob/master/so_pysm_models/tests/test_extragalactic.py

**Comment by ajvanengelen** [comment]
I am happy to save this in FITS format rather than a numpy binary file - could you point me to a piece of code that stores a 1d array in FITS, in such a way that it will get read in properly?

________________________________

**Comment by ajvanengelen** [comment]
Just a note that this is a bit of a funny mixture, as in the current plan these B modes from tensors will not be lensed, and also we are not making any T fluctuations from these tensors

**Comment by zonca** [comment]
@ajvanengelen I am implementing this, so here is a plot of your spectra:

![image](https://user-images.githubusercontent.com/383090/80138056-15a5ea80-8559-11ea-9464-0ad6f0dd8500.png)

So just to confirm, to add tensor modes to the existing lensed/unlensed CMB spectra which are already in `so_pysm_models` (https://so-pysm-models.readthedocs.io/en/latest/models.html#websky) I just use the BB spectrum from this dataset and discard the rest. Right?

**Comment by ajvanengelen** [comment]
Hi Andrea,

Yes, I think that is our current plan. (It is not really internally consistent physically, but it is the most straightforward path toward ensuring that the sims contain both lensed primary modes and primordial B modes.)

Thanks for implmenting this!

Alex
________________________________

**Comment by zonca** [comment]
@ajvanengelen I have implemented this and ran some simulations, however, as it is evident from the plot above, it looks like there is no more power after ell=600, even if your files are until ell=8000 or so.

See an example simulation looks like this:

![image](https://user-images.githubusercontent.com/383090/81896523-a0cb3c80-9569-11ea-95aa-42213185a782.png)

do you mind to produce another file with power all the way to 8000?

**Comment by ajvanengelen** [comment]
I am not sure why this is happening, as I do `pars.set_for_lmax(10000, lens_potential_accuracy=2)` in my CAMB run.  I don't see a separate function to set the accuracy parameters different for tensors vs. scalars.  Given how strongly the primordial BB signal is suppressed on scales smaller than the horizon scale at decoupling, though, does this lmax=600 matter in practice?

**Comment by zonca** [comment]
I don't know, you are the expert, you confirm `lmax=600` is fine, I will write that in the docs and be done.

**Comment by ajvanengelen** [comment]
ok :) let's write that in the docs, hopefully it is ok.  Sorry for the confusion about this!

**Comment by zonca** [comment]
ok, thank you!

**Comment by keskitalo** [comment]
A colleague just discovered that scaling the tensor modes to match a specific value of `r` is inaccurate because the tensor spectral index, `n_t`, is set by the consistency relation: `n_t  = -r/8`. When the tensor mode spectrum is scaled, the spectral index is not adjusted to match the new `r`. This is particularly problematic if the fiducial value of `r` is chosen as `1` and not some small, more representative value.

**Comment by ajvanengelen** [comment]
Whoops - I agree that this is an issue with these spectra.  I didn't realize that if `n_t` is unspecified in the python camb, it is set to be `-r/8`.  I will do a new run with `n_t` set to 0.

Given that I will be rerunning this, Andrea, what is your preferred data format?  I sent numpy.save files last time, but would you prefer .fits?

**Comment by zonca** [comment]
best is the same format as last time, I have already a notebook that does the conversion

**Comment by zonca** [comment]
@ajvanengelen any update on this?

**Comment by ajvanengelen** [comment]
Sorry for the delay, please have a look now at `/global/cscratch1/sd/engelen/websky_BB_from_tensors_r_eq_1.npz.npy` on nersc/cori.

**Comment by zonca** [comment]
thanks @ajvanengelen see comparison between new and old spectra

![image](https://user-images.githubusercontent.com/383090/83549645-7c081c00-a4ba-11ea-89df-095b7299543e.png)

also changed the scaling to compare more easily with something like: https://lambda.gsfc.nasa.gov/graphics/bb_upperlimits/bb_limits_2015apr.pdf

**Comment by zonca** [comment]
ok, I updated the cl fits file at https://portal.nersc.gov/project/cmb/so_pysm_models_data/websky/0.3/

**Comment by zonca** [comment]
@ajvanengelen can you please attach here or put in a gist the script you used to generate this?

**Comment by ajvanengelen** [comment]
Sure - https://github.com/ajvanengelen/webskylensing/blob/master/py/test_cmb_powerspectra.py - as you can see, this calls my `get_cmb_powerspectra.websky_cmb_spectra` routine which is in the same directory.  

It is just a wrapper around CAMB that sets the cosmo parameters to be those used in the websky sims, and then (I think) packages the results into the ordering that the pixell tools expect for making alm's.

**Comment by zonca** [comment]
ok thanks

**Comment by zonca** [comment]
@ajvanengelen I am running some checks on the CMB tensor modes,
I wanted to check with you my implementation:

you simulated the CMB tensor modes with `r = 1`, if I want to simulate instead `r=1e-3`, I should multiply the TT, EE, BB power spectrum (not the map) by 1e-3, correct?

**Comment by zonca** [comment]
correct, `r` is defined as ratio of the `C_ell` so it is in power, if I am weighting the map, I use the sqrt.
