### ISSUE TITLE
Cosmological parameters in Websky

### ISSUE THREAD

**Issue by zonca** [simonsobs/so_pysm_models#49]
In the docs about websky at https://so-pysm-models.readthedocs.io/en/latest/models.html#websky

we would like to have all information about the cosmological parameters used in the Websky CMB.

@marcelo-alvarez can you please add that?
Make sure also `N_eff` is included.

You can edit https://github.com/simonsobs/so_pysm_models/blob/master/docs/models.rst directly online and make a pull request.

**Comment by zonca** [comment]
@ajvanengelen maybe you can help here as well? thanks!

**Comment by ajvanengelen** [comment]
Hi, the cosmo parameters for the websky CMB are set at https://github.com/ajvanengelen/webskylensing/blob/master/py/get_cmb_powerspectra.py

N_eff is just the CAMB default, which should be 3.046.

**Comment by zonca** [comment]
ok, thanks @ajvanengelen I'll add it to the docs
