### ISSUE TITLE
Websky cosmology in unlensed CMB

### ISSUE THREAD

**Issue by msyriac** [simonsobs/so_pysm_models#54]
@ajvanengelen @zonca  is the CAMB parameter file for the websky unlensed CMB available somewhere? This is needed to fully specify the model (e.g. tau).

**Comment by ajvanengelen** [comment]
Yes - please see the values in this python file: https://github.com/ajvanengelen/webskylensing/blob/master/py/get_cmb_powerspectra.py

These are tuned to match the parameters in the large-scale structure sims run by George & Marcelo.

**Comment by zonca** [comment]
thanks @ajvanengelen,
for reference, it is mentioned in the docs: https://so-pysm-models.readthedocs.io/en/latest/models.html#websky
