### ISSUE TITLE
Detailed documentation about foreground models

### ISSUE THREAD

**Issue by zonca** [simonsobs/so_pysm_models#6]
I've setup readthedocs to build documentation, so we can expand a bit what we have in the docstrings, in particular it supports mathjax so we can have Latex equations, see https://so-pysm-models.readthedocs.io/en/latest/so_pysm_models/models.html#synchrotron

@NicolettaK I pasted there your description from the Pull Request so it doesn't get lost, can you please clean it up and improve upon it?
There is a "Edit this page on Github" page at the bottom of the page for convenience.

**Comment by NicolettaK** [comment]
https://github.com/NicolettaK/so_pysm_models/blob/docs/docs/so_pysm_models/models.rst 

I wrote here the documentation for GaussianSynch and Dust.
Sorry for the delay.

**Comment by zonca** [comment]
Thanks, can you make a pull request to this repo?

**Comment by zonca** [comment]
Closed by #9
